baseURL = "https://offensivedefence.co.uk"
title = "Offensive Defence"
themesDir = "themes"
theme = "m10c"
paginate = 5

[params]
  description = "\"The hand which strikes also blocks.\""

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
unsafe= true